#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(CHARM) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FAKE_TEARS) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(MUD_SLAP) \
    F(OVERHEAT) \
    F(FIRE_FANG) \
    F(THUNDER_FANG) \
    F(ICE_FANG) \
    F(LOW_KICK) \
    F(ACROBATICS) \
    F(STRUGGLE_BUG) \
    F(DISARMING_VOICE) \
    F(TRAILBLAZE) \
    F(POUNCE) \
    F(CHILLING_WATER) \
    F(POISON_TAIL) \
    F(BULLDOZE) \
    F(HEX) \
    F(SNARL) \
    F(SWIFT) \
    F(MAGICAL_LEAF) \
    F(ICY_WIND) \
    F(FLAME_CHARGE) \
    F(AIR_CUTTER) \
    F(DRAGON_TAIL) \
    F(VENOSHOCK) \
    F(VOLT_SWITCH) \
    F(SNOWSCAPE) \
    F(SMART_STRIKE) \
    F(PSYSHOCK) \
    F(U_TURN) \
    F(FOUL_PLAY) \
    F(PSYCHIC_FANGS) \
    F(SEED_BOMB) \
    F(DRAIN_PUNCH) \
    F(DAZZLING_GLEAM) \
    F(THUNDER_WAVE) \
    F(POISON_JAB) \
    F(STOMPING_TANTRUM) \
    F(ROCK_SLIDE) \
    F(BODY_PRESS) \
    F(SPIKES) \
    F(TOXIC_SPIKES) \
    F(FLASH_CANNON) \
    F(DARK_PULSE) \
    F(LEECH_LIFE) \
    F(EERIE_IMPULSE) \
    F(IRON_HEAD) \
    F(DRAGON_DANCE) \
    F(POWER_GEM) \
    F(GUNK_SHOT) \
    F(IRON_DEFENSE) \
    F(DRILL_RUN) \
    F(WILL_O_WISP) \
    F(LIQUIDATION)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
